/* const countryList = {
  "AFG": "AF",
  "ALA": "AX",
  "ALB": "AL",
  "DZA": "DZ",
  "ASM": "AS",
  "AND": "AD",
  "AGO": "AO",
  "AIA": "AI",
  "ATA": "AQ",
  "ATG": "AG",
  "ARG": "AR",
  "ARM": "AM",
  "ABW": "AW",
  "AUS": "AU",
  "AUT": "AT",
  "AZE": "AZ",
  "BHS": "BS",
  "BHR": "BH",
  "BGD": "BD",
  "BRB": "BB",
  "BLR": "BY",
  "BEL": "BE",
  "BLZ": "BZ",
  "BEN": "BJ",
  "BMU": "BM",
  "BTN": "BT",
  "BOL": "BO",
  "BES": "BQ",
  "BIH": "BA",
  "BWA": "BW",
  "BVT": "BV",
  "BRA": "BR",
  "IOT": "IO",
  "BRN": "BN",
  "BGR": "BG",
  "BFA": "BF",
  "BDI": "BI",
  "CPV": "CV",
  "KHM": "KH",
  "CMR": "CM",
  "CAN": "CA",
  "CYM": "KY",
  "CAF": "CF",
  "TCD": "TD",
  "CHL": "CL",
  "CHN": "CN",
  "CXR": "CX",
  "CCK": "CC",
  "COL": "CO",
  "COM": "KM",
  "COG": "CG",
  "COD": "CD",
  "COK": "CK",
  "CRI": "CR",
  "CIV": "CI",
  "HRV": "HR",
  "CUB": "CU",
  "CUW": "CW",
  "CYP": "CY",
  "CZE": "CZ",
  "DNK": "DK",
  "DJI": "DJ",
  "DMA": "DM",
  "DOM": "DO",
  "ECU": "EC",
  "EGY": "EG",
  "SLV": "SV",
  "GNQ": "GQ",
  "ERI": "ER",
  "EST": "EE",
  "SWZ": "SZ",
  "ETH": "ET",
  "FLK": "FK",
  "FRO": "FO",
  "FJI": "FJ",
  "FIN": "FI",
  "FRA": "FR",
  "GUF": "GF",
  "PYF": "PF",
  "ATF": "TF",
  "GAB": "GA",
  "GMB": "GM",
  "GEO": "GE",
  "DEU": "DE",
  "GHA": "GH",
  "GIB": "GI",
  "GRC": "GR",
  "GRL": "GL",
  "GRD": "GD",
  "GLP": "GP",
  "GUM": "GU",
  "GTM": "GT",
  "GGY": "GG",
  "GIN": "GN",
  "GNB": "GW",
  "GUY": "GY",
  "HTI": "HT",
  "HMD": "HM",
  "VAT": "VA",
  "HND": "HN",
  "HKG": "HK",
  "HUN": "HU",
  "ISL": "IS",
  "IND": "IN",
  "IDN": "ID",
  "IRN": "IR",
  "IRQ": "IQ",
  "IRL": "IE",
  "IMN": "IM",
  "ISR": "IL",
  "ITA": "IT",
  "JAM": "JM",
  "JPN": "JP",
  "JEY": "JE",
  "JOR": "JO",
  "KAZ": "KZ",
  "KEN": "KE",
  "KIR": "KI",
  "PRK": "KP",
  "KOR": "KR",
  "KWT": "KW",
  "KGZ": "KG",
  "LAO": "LA",
  "LVA": "LV",
  "LBN": "LB",
  "LSO": "LS",
  "LBR": "LR",
  "LBY": "LY",
  "LIE": "LI",
  "LTU": "LT",
  "LUX": "LU",
  "MAC": "MO",
  "MDG": "MG",
  "MWI": "MW",
  "MYS": "MY",
  "MDV": "MV",
  "MLI": "ML",
  "MLT": "MT",
  "MHL": "MH",
  "MTQ": "MQ",
  "MRT": "MR",
  "MUS": "MU",
  "MYT": "YT",
  "MEX": "MX",
  "FSM": "FM",
  "MDA": "MD",
  "MCO": "MC",
  "MNG": "MN",
  "MNE": "ME",
  "MSR": "MS",
  "MAR": "MA",
  "MOZ": "MZ",
  "MMR": "MM",
  "NAM": "NA",
  "NRU": "NR",
  "NPL": "NP",
  "NLD": "NL",
  "NCL": "NC",
  "NZL": "NZ",
  "NIC": "NI",
  "NER": "NE",
  "NGA": "NG",
  "NIU": "NU",
  "NFK": "NF",
  "MNP": "MP",
  "NOR": "NO",
  "OMN": "OM",
  "PAK": "PK",
  "PLW": "PW",
  "PSE": "PS",
  "PAN": "PA",
  "PNG": "PG",
  "PRY": "PY",
  "PER": "PE",
  "PHL": "PH",
  "PCN": "PN",
  "POL": "PL",
  "PRT": "PT",
  "PRI": "PR",
  "QAT": "QA",
  "REU": "RE",
  "ROU": "RO",
  "RUS": "RU",
  "RWA": "RW",
  "BLM": "BL",
  "SHN": "SH",
  "KNA": "KN",
  "LCA": "LC",
  "MAF": "MF",
  "SPM": "PM",
  "VCT": "VC",
  "WSM": "WS",
  "SMR": "SM",
  "STP": "ST",
  "SAU": "SA",
  "SEN": "SN",
  "SRB": "RS",
  "SYC": "SC",
  "SLE": "SL",
  "SGP": "SG",
  "SXM": "SX",
  "SVK": "SK",
  "SVN": "SI",
  "SLB": "SB",
  "SOM": "SO",
  "ZAF": "ZA",
  "SGS": "GS",
  "SSD": "SS",
  "ESP": "ES",
  "LKA": "LK",
  "SDN": "SD",
  "SUR": "SR",
  "SJM": "SJ",
  "SWE": "SE",
  "CHE": "CH",
  "SYR": "SY",
  "TWN": "TW",
  "TJK": "TJ",
  "TZA": "TZ",
  "THA": "TH",
  "TLS": "TL",
  "TGO": "TG",
  "TKL": "TK",
  "TON": "TO",
  "TTO": "TT",
  "TUN": "TN",
  "TUR": "TR",
  "TKM": "TM",
  "TCA": "TC",
  "TUV": "TV",
  "UGA": "UG",
  "UKR": "UA",
  "ARE": "AE",
  "GBR": "GB",
  "USA": "US",
  "UMI": "UM",
  "URY": "UY",
  "UZB": "UZ",
  "VUT": "VU",
  "VEN": "VE",
  "VNM": "VN",
  "VGB": "VG",
  "VIR": "VI",
  "WLF": "WF",
  "ESH": "EH",
  "YEM": "YE",
  "ZMB": "ZM",
  "ZWE": "ZW"
};

 */
const countryList = {
  "INR": "IN",
  "AED": "AE", "AFN": "AF", "ALL": "AL", "AMD": "AM", "ANG": "NL",
  "AOA": "AO", "ARS": "AR", "AUD": "AU", "AWG": "AW", "AZN": "AZ",
  "BAM": "BA", "BBD": "BB", "BDT": "BD", "BGN": "BG", "BHD": "BH",
  "BIF": "BI", "BMD": "BM", "BND": "BN", "BOB": "BO", "BRL": "BR",
  "BSD": "BS", "BTN": "BT", "BWP": "BW", "BYN": "BY", "BZD": "BZ",
  "CAD": "CA", "CDF": "CD", "CHF": "CH", "CLP": "CL", "CNY": "CN",
  "COP": "CO", "CRC": "CR", "CUP": "CU", "CVE": "CV", "CZK": "CZ",
  "DJF": "DJ", "DKK": "DK", "DOP": "DO", "DZD": "DZ", "EGP": "EG",
  "ERN": "ER", "ETB": "ET", "EUR": "EU", "FJD": "FJ", "FKP": "FK",
  "GBP": "GB", "GEL": "GE", "GHS": "GH", "GIP": "GI", "GMD": "GM",
  "GNF": "GN", "GTQ": "GT", "GYD": "GY", "HKD": "HK", "HNL": "HN",
  "HRK": "HR", "HTG": "HT", "HUF": "HU", "IDR": "ID", "ILS": "IL",
   "IQD": "IQ", "IRR": "IR", "ISK": "IS", "JMD": "JM",
  "JOD": "JO", "JPY": "JP", "KES": "KE", "KGS": "KG", "KHR": "KH",
  "KMF": "KM", "KRW": "KR", "KWD": "KW", "KYD": "KY", "KZT": "KZ",
  "LAK": "LA", "LBP": "LB", "LKR": "LK", "LRD": "LR", "LSL": "LS",
  "LYD": "LY", "MAD": "MA", "MDL": "MD", "MGA": "MG", "MKD": "MK",
  "MMK": "MM", "MNT": "MN", "MOP": "MO", "MRU": "MR", "MUR": "MU",
  "MVR": "MV", "MWK": "MW", "MXN": "MX", "MYR": "MY", "MZN": "MZ",
  "NAD": "NA", "NGN": "NG", "NIO": "NI", "NOK": "NO", "NPR": "NP",
  "NZD": "NZ", "OMR": "OM", "PAB": "PA", "PEN": "PE", "PGK": "PG",
  "PHP": "PH", "PKR": "PK", "PLN": "PL", "PYG": "PY", "QAR": "QA",
  "RON": "RO", "RSD": "RS", "RUB": "RU", "RWF": "RW", "SAR": "SA",
  "SBD": "SB", "SCR": "SC", "SDG": "SD", "SEK": "SE", "SGD": "SG",
  "SHP": "SH", "SLL": "SL", "SOS": "SO", "SRD": "SR", "STN": "ST",
  "SVC": "SV", "SYP": "SY", "SZL": "SZ", "THB": "TH", "TJS": "TJ",
  "TMT": "TM", "TND": "TN", "TOP": "TO", "TRY": "TR", "TTD": "TT",
  "TWD": "TW", "TZS": "TZ", "UAH": "UA", "UGX": "UG", "USD": "US",
  "UYU": "UY", "UZS": "UZ", "VND": "VN", "VUV": "VU", "WST": "WS",
  "XAF": "CF", "XCD": "LC", "XOF": "SN", "XPF": "PF", "YER": "YE",
  "ZAR": "ZA", "ZMW": "ZM", "ZWL": "ZW"
};
